# Generated by Django 2.1.5 on 2019-09-19 21:27

from django.db import migrations, models
import website.validators


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='event_pictures', validators=[website.validators.image_restriction]),
        ),
    ]
